apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: public.ecr.aws/p4z1i4n3/wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: rds-mysql-service
        - name: WORDPRESS_DB_PORT
          value: "3306"              
        - name: WORDPRESS_DB_USER
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key:  WORDPRESS_DB_USER        
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key:  WORDPRESS_DB_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key:  WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
