apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-with-loadbalancer
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

  selector:
    app: wordpress

---
# create ExternalName service to connect rds
apiVersion: v1
kind: Service
metadata:
  name: rds-mysql-service
spec:
  type: ExternalName
  externalName: mydbinstance.cxfcp6cl0duj.us-east-1.rds.amazonaws.com #Replace with rds endpoint
