apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: public.ecr.aws/p4z1i4n3/wordpress:latest
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress